### ISSUE TITLE
SNMP unchecked after reboot

### ISSUE THREAD

**Issue by digitlman** [zevenet/zlb#31]
Latest CE v5 with latest cluster services installed.

I have SNMP enabled on each node.   When I reboot the node, the SNMP service gets un-checked and I have to re-check it to get it started again.

**Comment by emiliocampos-zevenet** [comment]
Hi @digitlman , I have been checking Zevenet CEv5 and snmp is enabled after a reboot, how did you install zevenet5? Did you use our ISO file downloaded from sourceforge? 

If you installed zevenet ce from repositories or you are running a container then you have to ensure the system includes update-rc.d binary

update-rc.d snmpd enable

This command starts snmpd daemon after any reboot. 

Thanks

**Comment by digitlman** [comment]
per https://serverfault.com/questions/71569/snmpd-not-binding-correctly

The settings in the snmpd.conf that Zevenet created had the LAN ip address.  I changed that to 0.0.0.0:161, rebooted, and the service started correctly.

**Comment by emiliocampos-zevenet** [comment]
Ohh now I am able to figure out now what is going on, because the first comment was not enough to understand what you did to configure the service.

 You selected a given IP where to bind SNMP service instead of run snmp in all the interfaces. In boot time snmp service starts at the same time than zevenet service (responsible of configuring network) so at the moment snmp runs and tries to bind in a given IP, this IP is not yet configured by zevenet service, so in order to solve this issue you only have to allow to bind services to non configured IPs as follows:

open /etc/sysct.conf file and add the next line:

net.ipv4.ip_nonlocal_bind=1

save changes and apply the value with 

sysctl -p

Change now the snmp service from zevenet gui to the desired IP and the service will run properly after a reboot. 

Thanks!

**Comment by emiliocampos-zevenet** [comment]
Closed after a while without updated information.
