### ISSUE TITLE
Adding backend to service having the same name as the HTTP farm breaks pound config

### ISSUE THREAD

**Issue by fkollmann** [zevenet/zlb#49]
# System

`cat /etc/zevenet_version` --> `ZCE 6`
`apt list zevenet` --> `zevenet/buster,now 5.9.1 amd64 [installed]`

Reproduce:

The following steps work both using ZAPI v3.1, v4.0 and the Web UI.

1) Create new HTTP Farm "test1234" on virtual interface
2) Add service "test1234" (use the *same* name as the farm name is.)
3) Add backend 
4) Try restart

# Error

`Error in the parameter BackEnd in the service test1234`

# Workaround

Remove the extra *BackEnd* .... *End* block below the *Service*-comment-block.

Best Regards, Felix

**Comment by crissty** [comment]
Hi fkollmann,
We have reproduced the issue, we are going to work on it, and we will be notify when it is solved.
Thank you so much for the report!

**Comment by cano-devel** [comment]
Hello @fkollmann 

we want to announce to you that we have released a new version and this issue is solved. We invite you to upgrade and test it.

Remember the new package upgrades are available through the apt repository. You only will have to execute:
"apt-update && apt-installl zevenet*"

We pass to close the ticket,
thanks for your time and sorry for the delay, have a good day!
