### ISSUE TITLE
feature request header enrichment

### ISSUE THREAD

**Issue by iddq** [zevenet/zlb#63]
header enrichment. add custom header to traffic towards backends.

**Comment by emiliocampos-zevenet** [comment]
Hi, this feature is totally supported from the http proxy server zproxy but it is not integrated in the GUI, we will register this feature as a new option in the http profile. 

Meanwhile refer to zproxy manual documentation if you want to add/remove headers to backends in https://github.com/zevenet/zproxy/blob/master/docs/zproxy.8 AddHeader and HeaderRemove directives. 

Thanks

**Comment by iddq** [comment]
Thank you. Is it available in the community version?

I don't find zproxy in ZCE 6.

cat /etc/zevenet_version
ZCE 6

**Comment by adanmarin-zevenet** [comment]
Good day,

you can execute the following command to check that zproxy is installed in the system:

**dpkg -l | grep zproxy**

The command output should be:
ii zproxy 0.1.61-5.11.0 amd64 Zevenet zproxy

otherwise, to upgrade to the latest version of zproxy, you can execute the following command:

**apt-get update && apt-get install zproxy**

Once updated, you can try to modify the farm configuration file and change the AddHeader and HeaderRemove directives.

**Comment by adanmarin-zevenet** [comment]
Good day,
did you have the chance to apply the solution I mentioned before?

**Comment by iddq** [comment]
Hello, Thank you for the help. I haven't tried it out and it is out of scope now.
